### ISSUE TITLE
Paper recommendation

### ISSUE THREAD

**Issue by GRAPH-0** [qingsongedu/awesome-self-supervised-learning-timeseries#1]
Hi,

Thanks for your excellent survey on time series!
Would you mind considering our paper published on ICDE 2023 about diffusion-based imputation models for spatiotemporal time series?
Title: PriSTI: A Conditional Diffusion Framework for Spatiotemporal Imputation
Paper Link: https://arxiv.org/abs/2302.09746
Code Link: https://github.com/LMZZML/PriSTI

**Comment by qingsongedu** [comment]
Thanks for the suggestion. Just updated it.
