### ISSUE TITLE
Paper recommendation

### ISSUE THREAD

**Issue by realwangjiahao** [qingsongedu/awesome-self-supervised-learning-timeseries#2]
Thank you for summarizing these . It is very helpful to my study of time series.

I am very interested in the Autoencoder-based reconstruction part, and your summary is also very comprehensive.
I recently read a paper about pre-training. The author proposes TimeMAE, a novel self-supervised paradigm for learning transferrable time series representations based on transformer networks. The idea of this paper is great, and the experimental results are also very good.
Could you please read this article and add it to your Autoencoder-based reconstruction part？
You can find this article at https://arxiv.org/abs/2303.00320
You can find code at https://github.com/Mingyue-Cheng/TimeMAE

With best regards.

**Comment by qingsongedu** [comment]
Thanks for the suggestion. Just updated it.
