### ISSUE TITLE
Paper recommendation

### ISSUE THREAD

**Issue by lanxiang1017** [qingsongedu/awesome-self-supervised-learning-timeseries#4]
Hi, thanks for the great survey! Would you mind adding two papers to your updated repo or arxiv? Many thanks! 

paper: Intra-Inter Subject Self-Supervised Learning for Multivariate Cardiac Signals [AAAI 22]
link: https://ojs.aaai.org/index.php/AAAI/article/view/20376
category: domain application of time series
about: we proposed a SSL framework for multivariate cardiac signals.

bib:
@<span>article<span>{Lan_Ng_Hong_Feng_2022, 
	title={Intra-Inter Subject Self-Supervised Learning for Multivariate Cardiac Signals}, 
	volume={36}, 
	url={https://ojs.aaai.org/index.php/AAAI/article/view/20376}, 
	DOI={10.1609/aaai.v36i4.20376}, 
	number={4}, 
	journal={Proceedings of the AAAI Conference on Artificial Intelligence}, 
	author={Lan, Xiang and Ng, Dianwen and Hong, Shenda and Feng, Mengling}, 
	year={2022}, 
	month={Jun.}, 
	pages={4532-4540}
}

paper: Towards Enhancing Time Series Contrastive Learning: A Dynamic Bad Pair Mining Approach [ICLR 24]
link: https://openreview.net/pdf?id=K2c04ulKXn
category: time series contrastive learning
about: we investigated the bad positive pair problem in time series contrastive learning.

bib:
@inproceedings{lan2024towards,
	title={Towards Enhancing Time Series Contrastive Learning: A Dynamic Bad Pair Mining Approach},
	author={Xiang Lan and Hanshu Yan and Shenda Hong and Mengling Feng},
	booktitle={The Twelfth International Conference on Learning Representations},
	year={2024},
	url={https://openreview.net/forum?id=K2c04ulKXn}
}

**Comment by qingsongedu** [comment]
Thanks for the comments. Just added the two papers.
